/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.examples.android.firebase

import com.google.adk.kt.annotations.Param
import com.google.adk.kt.annotations.Tool

/**
 * A trivial tool exposed to the Firebase-backed agent through the KSP `@Tool` processor. Calling
 * [com.google.adk.kt.examples.android.firebase.WeatherTools.generatedTools] (generated by the
 * processor) turns this into a `FunctionTool` the model can invoke.
 *
 * It always returns the same made-up temperature: a value the model cannot know on its own, which
 * makes it obvious in the transcript that the tool was actually called rather than the answer being
 * hallucinated.
 */
class WeatherTools {
  @Tool(
    name = "get_current_temperature",
    description = "Returns the current temperature in Celsius for a given location.",
  )
  fun getCurrentTemperature(
    @Param("The city to look up, e.g. 'Mountain View'.") location: String
  ): Map<String, Int> = mapOf("temperature_celsius" to 42)
}
