/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.types

import com.google.adk.kt.ids.Uuid
import kotlinx.serialization.Contextual
import kotlinx.serialization.EncodeDefault
import kotlinx.serialization.Serializable

/**
 * Represents a function call in a generation response.
 *
 * @property name The name of the function to call.
 * @property args The arguments to pass to the function.
 * @property id The unique identifier for this function call.
 * @property partialArgs Partial argument fragments being streamed from the model.
 * @property willContinue Whether more partial fragments for this function call are expected.
 */
@Serializable
data class FunctionCall(
  val name: String = "",
  // Always emit args (even empty {}) to match the genai/Python golden shape.
  @EncodeDefault(EncodeDefault.Mode.ALWAYS) val args: Map<String, @Contextual Any?> = emptyMap(),
  val id: String? = null,
  val partialArgs: List<PartialArg>? = null,
  val willContinue: Boolean? = null,
) {
  companion object {
    /** Prefix for client-side function call IDs generated by the ADK. */
    const val ADK_FUNCTION_CALL_ID_PREFIX = "adk-"

    /** Function name for requesting user credentials. */
    const val REQUEST_EUC_FUNCTION_CALL_NAME = "adk_request_credential"

    /** Function name for requesting user confirmation for a tool execution. */
    const val REQUEST_CONFIRMATION_FUNCTION_CALL_NAME = "adk_request_confirmation"

    /** Key used in the arguments map to store the original function call being confirmed. */
    const val ORIGINAL_FUNCTION_CALL_KEY = "originalFunctionCall"

    /** Key used in the arguments map to store the tool confirmation result. */
    const val TOOL_CONFIRMATION_KEY = "toolConfirmation"

    /** Key for the function name in the serialized function call map. */
    const val NAME_KEY = "name"

    /** Key for the function arguments in the serialized function call map. */
    const val ARGS_KEY = "args"

    /** Key for the function call ID in the serialized function call map. */
    const val ID_KEY = "id"

    /** Generates a new unique client function call ID prefixed with ADK identifier. */
    fun generateId(): String {
      return "$ADK_FUNCTION_CALL_ID_PREFIX${Uuid.random()}"
    }
  }
}
