/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.kt.apps

import com.google.adk.kt.agents.BaseAgent
import com.google.adk.kt.agents.ContextCacheConfig
import com.google.adk.kt.agents.ContextFrameworkData
import com.google.adk.kt.agents.InvocationContext
import com.google.adk.kt.agents.InvocationCostManager
import com.google.adk.kt.agents.ResumabilityConfig
import com.google.adk.kt.agents.RunConfig
import com.google.adk.kt.agents.StreamingMode
import com.google.adk.kt.artifacts.ArtifactService
import com.google.adk.kt.events.Event
import com.google.adk.kt.events.EventActions
import com.google.adk.kt.memory.MemoryService
import com.google.adk.kt.models.CacheMetadata
import com.google.adk.kt.models.Gemini
import com.google.adk.kt.models.LlmResponse
import com.google.adk.kt.models.VertexCredentials
import com.google.adk.kt.plugins.PluginManager
import com.google.adk.kt.sessions.Session
import com.google.adk.kt.sessions.SessionService
import com.google.adk.kt.summarizer.EventsCompactionConfig
import com.google.adk.kt.testing.DummyAgent
import com.google.adk.kt.testing.modelMessage
import com.google.adk.kt.testing.testSession
import com.google.adk.kt.types.ActivityHandling
import com.google.adk.kt.types.AudioTranscriptionConfig
import com.google.adk.kt.types.Citation
import com.google.adk.kt.types.CitationMetadata
import com.google.adk.kt.types.Content
import com.google.adk.kt.types.ContextWindowCompressionConfig
import com.google.adk.kt.types.FinishReason
import com.google.adk.kt.types.FunctionDeclaration
import com.google.adk.kt.types.GroundingMetadata
import com.google.adk.kt.types.HarmBlockThreshold
import com.google.adk.kt.types.HarmCategory
import com.google.adk.kt.types.LiveConnectConfig
import com.google.adk.kt.types.LogprobsResult
import com.google.adk.kt.types.MediaResolution
import com.google.adk.kt.types.Modality
import com.google.adk.kt.types.Part
import com.google.adk.kt.types.ProactivityConfig
import com.google.adk.kt.types.RealtimeInputConfig
import com.google.adk.kt.types.Role
import com.google.adk.kt.types.SafetySetting
import com.google.adk.kt.types.SessionResumptionConfig
import com.google.adk.kt.types.SpeechConfig
import com.google.adk.kt.types.ThinkingConfig
import com.google.adk.kt.types.Tool
import com.google.adk.kt.types.UsageMetadata
import com.google.adk.kt.types.VoiceActivity
import com.google.adk.kt.workflow.NodeInfo
import java.io.ByteArrayOutputStream
import java.net.URLClassLoader
import javax.tools.ToolProvider
import kotlin.io.path.createTempDirectory
import kotlin.io.path.writeText
import kotlin.jvm.internal.DefaultConstructorMarker
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertSame
import kotlin.test.assertTrue
import kotlin.time.Duration.Companion.milliseconds

/**
 * Code built against an earlier release must keep linking to the constructors below. Some also keep
 * the synthetic constructor that fills in default arguments; those generated by `@JvmOverloads`
 * don't, so Kotlin code that relied on their default arguments must recompile. Java source
 * recompiled against this version must bind to the same constructors, which only javac can check.
 */
class ReleasedConstructorsTest {

  @Test
  fun app_releasedConstructorWithDefaults_stillLinksAndLeavesRootNodeUnset() {
    // Arrange: 1.1.0 `App(appName, rootAgent)`, compiled with every later argument defaulted.
    val agent = DummyAgent(name = "root")
    val constructor =
      App::class
        .java
        .getConstructor(
          *RELEASED_APP_PARAMETERS,
          Int::class.java,
          DefaultConstructorMarker::class.java,
        )

    // Act
    val app = constructor.newInstance("my_app", agent, null, null, null, null, 0b111100, null)

    // Assert
    assertEquals("my_app", app.appName)
    assertSame(agent, app.rootAgent)
    assertEquals(emptyList(), app.plugins)
    assertNull(app.rootNode)
  }

  @Test
  fun app_releasedFullConstructor_stillLinks() {
    // Arrange
    val agent = DummyAgent(name = "root")
    val resumability = ResumabilityConfig(isResumable = true)

    // Act
    val app =
      App::class
        .java
        .getConstructor(*RELEASED_APP_PARAMETERS)
        .newInstance("my_app", agent, emptyList<Any>(), resumability, null, null)

    // Assert
    assertSame(resumability, app.resumabilityConfig)
    assertNull(app.rootNode)
  }

  @Test
  fun gemini_releasedConstructors_resolveAndLeaveSpeechConfigUnset() {
    // Arrange: the released `Gemini` constructors, before `speechConfig` was added last.
    val client = Class.forName("com.google.genai.kotlin.Client")
    val string = String::class.java

    // Act / Assert: getConstructor throws if a released signature is gone, so resolving each one is
    // the check; the two-arg instance must still default speechConfig to null.
    val withKey =
      Gemini::class.java.getConstructor(string, string).newInstance("gemini-test", "fake-key")
    Gemini::class.java.getConstructor(string)
    Gemini::class.java.getConstructor(client, string)
    Gemini::class.java.getConstructor(string, VertexCredentials::class.java)

    assertNull(withKey.speechConfig)
  }

  @Test
  fun gemini_javaSourcePassingNullSpeechConfig_compilesAndLeavesItUnset() {
    // Arrange: a bare null third argument was ambiguous while a test-only (String, String, String)
    // constructor existed, because Java sees internal constructors.
    val caller =
      compileJava(
        "NullSpeechConfigGeminiCaller",
        """
        import com.google.adk.kt.models.Gemini;

        public final class NullSpeechConfigGeminiCaller {
          public static Gemini create() {
            return new Gemini("gemini-test", "fake-key", null);
          }
        }
        """,
      )

    // Act
    val gemini = caller.getMethod("create").invoke(null) as Gemini

    // Assert
    assertNull(gemini.speechConfig)
  }

  @Test
  fun app_javaSourceWrittenAgainstTheReleasedApi_bindsToTheAgentConstructor() {
    // Arrange
    val agent = DummyAgent(name = "root")
    val caller =
      compileJava(
        "ReleasedAppCaller",
        """
        import com.google.adk.kt.agents.BaseAgent;
        import com.google.adk.kt.apps.App;
        import java.util.List;

        public final class ReleasedAppCaller {
          public static App create(BaseAgent agent) {
            return new App("my_app", agent, List.of(), null, null, null);
          }
        }
        """,
      )

    // Act
    val app = caller.getMethod("create", BaseAgent::class.java).invoke(null, agent) as App

    // Assert: `BaseAgent` is also a `Node`, so a wrong binding wraps the agent in a node view.
    assertSame(agent, app.rootAgent)
    assertNull(app.rootNode)
  }

  @Test
  fun invocationContext_releasedConstructorWithDefaults_stillLinksAndLeavesNodeUnset() {
    // Arrange: 1.1.0 `InvocationContext(session, agent = agent, branch = "b")`, compiled with the
    // other arguments defaulted. Bit i of the mask marks parameter i as defaulted.
    val session = testSession()
    val agent = DummyAgent(name = "root")
    val allDefaulted = (1 shl RELEASED_CONTEXT_PARAMETERS.size) - 1
    val mask = allDefaulted and 0b1101.inv()
    val arguments = arrayOfNulls<Any>(RELEASED_CONTEXT_PARAMETERS.size)
    arguments[0] = session
    arguments[2] = agent
    arguments[3] = "b"
    arguments[16] = false
    val constructor =
      InvocationContext::class
        .java
        .getConstructor(
          *RELEASED_CONTEXT_PARAMETERS,
          Int::class.java,
          DefaultConstructorMarker::class.java,
        )

    // Act
    val context = constructor.newInstance(*arguments, mask, null)

    // Assert
    assertSame(session, context.session)
    assertSame(agent, context.agent)
    assertEquals("b", context.branch)
    assertNull(context.node)
  }

  @Test
  fun invocationContext_javaSourceWrittenAgainstTheReleasedApi_compiles() {
    // Arrange
    val session = testSession()
    val agent = DummyAgent(name = "root")
    val caller =
      compileJava(
        "ReleasedContextCaller",
        """
        import com.google.adk.kt.agents.BaseAgent;
        import com.google.adk.kt.agents.ContextFrameworkData;
        import com.google.adk.kt.agents.InvocationContext;
        import com.google.adk.kt.agents.InvocationCostManager;
        import com.google.adk.kt.plugins.PluginManager;
        import com.google.adk.kt.sessions.Session;
        import java.util.HashMap;

        public final class ReleasedContextCaller {
          public static InvocationContext create(
              Session session,
              BaseAgent agent,
              ContextFrameworkData frameworkData,
              PluginManager pluginManager) {
            return new InvocationContext(
                session, null, agent, "b", "inv-1", null, null, null, null, null, null, null,
                new HashMap<>(), new HashMap<>(), new HashMap<>(), frameworkData, false,
                pluginManager, new InvocationCostManager());
          }
        }
        """,
      )

    // Act
    val context =
      caller
        .getMethod(
          "create",
          Session::class.java,
          BaseAgent::class.java,
          ContextFrameworkData::class.java,
          PluginManager::class.java,
        )
        .invoke(null, session, agent, ContextFrameworkData(), PluginManager()) as InvocationContext

    // Assert
    assertSame(agent, context.agent)
    assertEquals("b", context.branch)
    assertEquals("inv-1", context.invocationId)
    assertNull(context.node)
  }

  @Test
  fun llmResponse_releasedFullConstructor_stillLinks() {
    // Arrange: distinct non-default values for all 14 released parameters, so a swap is caught.
    val content = modelMessage("hi")
    val usageMetadata = UsageMetadata(totalTokenCount = 3)
    val finishReason = FinishReason.MAX_TOKENS
    val errorMessage = "truncated"
    val partial = true
    val interrupted = true
    val modelVersion = "v1"
    val citationMetadata = CitationMetadata()
    val groundingMetadata = GroundingMetadata(webSearchQueries = listOf("query"))
    val errorCode = "MAX_TOKENS"
    val customMetadata = mapOf("key" to "value")
    val avgLogprobs = -0.5
    val logprobsResult = LogprobsResult(logProbabilitySum = -1.5)
    val cacheMetadata = CacheMetadata(fingerprint = "abc", contentsCount = 2)

    // Act
    val response =
      LlmResponse::class
        .java
        .getConstructor(*RELEASED_LLM_RESPONSE_PARAMETERS)
        .newInstance(
          content,
          usageMetadata,
          finishReason,
          errorMessage,
          partial,
          interrupted,
          modelVersion,
          citationMetadata,
          groundingMetadata,
          errorCode,
          customMetadata,
          avgLogprobs,
          logprobsResult,
          cacheMetadata,
        )

    // Assert
    assertEquals(
      LlmResponse(
        content = content,
        usageMetadata = usageMetadata,
        finishReason = finishReason,
        errorMessage = errorMessage,
        partial = partial,
        interrupted = interrupted,
        modelVersion = modelVersion,
        citationMetadata = citationMetadata,
        groundingMetadata = groundingMetadata,
        errorCode = errorCode,
        customMetadata = customMetadata,
        avgLogprobs = avgLogprobs,
        logprobsResult = logprobsResult,
        cacheMetadata = cacheMetadata,
      ),
      response,
    )
  }

  @Test
  fun llmResponse_releasedNoArgConstructor_stillLinks() {
    // Arrange / Act: the released class had a no-arg constructor; all its params had defaults.
    val response = LlmResponse::class.java.getConstructor().newInstance()

    // Assert
    assertEquals(LlmResponse(), response)
  }

  @Test
  fun llmResponse_javaSourceWrittenAgainstTheReleasedApi_compiles() {
    // Arrange
    val caller =
      compileJava(
        "ReleasedLlmResponseCaller",
        """
        import com.google.adk.kt.models.LlmResponse;

        public final class ReleasedLlmResponseCaller {
          public static LlmResponse create() {
            return new LlmResponse(
                null, null, null, "e", true, false, null, null, null, null, null, null, null, null);
          }
        }
        """,
      )

    // Act
    val response = caller.getMethod("create").invoke(null) as LlmResponse

    // Assert
    assertEquals(LlmResponse(errorMessage = "e", partial = true), response)
    assertNull(response.turnComplete)
  }

  @Test
  fun runConfig_releasedFullConstructor_stillLinks() {
    // Arrange: distinct non-default values for all 3 released parameters, so a swap is caught.
    val streamingMode = StreamingMode.SSE
    val maxLlmCalls = 7
    val customMetadata = mapOf<String, Any>("k" to "v")

    // Act
    val config =
      RunConfig::class
        .java
        .getConstructor(*RELEASED_RUN_CONFIG_PARAMETERS)
        .newInstance(streamingMode, maxLlmCalls, customMetadata) as RunConfig

    // Assert
    assertEquals(
      RunConfig(
        streamingMode = streamingMode,
        maxLlmCalls = maxLlmCalls,
        customMetadata = customMetadata,
      ),
      config,
    )
  }

  @Test
  fun runConfig_releasedNoArgConstructor_stillLinks() {
    // Arrange / Act: the released class had a no-arg constructor; all its params had defaults.
    val config = RunConfig::class.java.getConstructor().newInstance()

    // Assert
    assertEquals(RunConfig(), config)
  }

  @Test
  fun runConfig_javaSourceWrittenAgainstTheReleasedApi_compiles() {
    // Arrange
    val caller =
      compileJava(
        "ReleasedRunConfigCaller",
        """
        import com.google.adk.kt.agents.RunConfig;
        import com.google.adk.kt.agents.StreamingMode;
        import java.util.Map;

        public final class ReleasedRunConfigCaller {
          public static RunConfig create() {
            return new RunConfig(StreamingMode.SSE, 7, Map.of("k", "v"));
          }
        }
        """,
      )

    // Act
    val config = caller.getMethod("create").invoke(null) as RunConfig

    // Assert
    assertEquals(
      RunConfig(
        streamingMode = StreamingMode.SSE,
        maxLlmCalls = 7,
        customMetadata = mapOf("k" to "v"),
      ),
      config,
    )
  }

  @Test
  fun liveConnectConfig_releasedFullConstructor_stillLinks() {
    // Arrange: a distinct non-default value for every one of the 19 released parameters, so a swap
    // is caught - including the two same-typed transcription fields.
    val modalities = listOf(Modality.AUDIO)
    val media = MediaResolution.MEDIA_RESOLUTION_LOW
    val speech = SpeechConfig(languageCode = "en-US")
    val thinking = ThinkingConfig(thinkingBudget = 1)
    val instruction = Content(role = Role.SYSTEM, parts = listOf(Part(text = "si")))
    val tools =
      listOf(
        Tool(functionDeclarations = listOf(FunctionDeclaration(name = "f", description = "d")))
      )
    val resumption = SessionResumptionConfig(handle = "h")
    val inputTranscription = AudioTranscriptionConfig(languageCodes = listOf("fr"))
    val outputTranscription = AudioTranscriptionConfig(languageCodes = listOf("de"))
    val realtime = RealtimeInputConfig(activityHandling = ActivityHandling.NO_INTERRUPTION)
    val compression = ContextWindowCompressionConfig(triggerTokens = 1024L)
    val proactivity = ProactivityConfig(proactiveAudio = true)
    val safety =
      listOf(
        SafetySetting(
          category = HarmCategory.HARM_CATEGORY_HARASSMENT,
          threshold = HarmBlockThreshold.BLOCK_NONE,
        )
      )
    val arguments =
      arrayOf<Any?>(
        modalities,
        0.1f,
        0.2f,
        3,
        4,
        media,
        6,
        speech,
        thinking,
        true,
        instruction,
        tools,
        resumption,
        inputTranscription,
        outputTranscription,
        realtime,
        compression,
        proactivity,
        safety,
      )

    // Act
    val config =
      LiveConnectConfig::class
        .java
        .getConstructor(*RELEASED_LIVE_CONNECT_CONFIG_PARAMETERS)
        .newInstance(*arguments) as LiveConnectConfig

    // Assert
    assertEquals(
      LiveConnectConfig(
        responseModalities = modalities,
        temperature = 0.1f,
        topP = 0.2f,
        topK = 3,
        maxOutputTokens = 4,
        mediaResolution = media,
        seed = 6,
        speechConfig = speech,
        thinkingConfig = thinking,
        enableAffectiveDialog = true,
        systemInstruction = instruction,
        tools = tools,
        sessionResumption = resumption,
        inputAudioTranscription = inputTranscription,
        outputAudioTranscription = outputTranscription,
        realtimeInputConfig = realtime,
        contextWindowCompression = compression,
        proactivity = proactivity,
        safetySettings = safety,
      ),
      config,
    )
  }

  @Test
  fun liveConnectConfig_releasedNoArgConstructor_stillLinks() {
    // Arrange / Act: the released class had a no-arg constructor; all its params had defaults.
    val config = LiveConnectConfig::class.java.getConstructor().newInstance()

    // Assert
    assertEquals(LiveConnectConfig(), config)
  }

  @Test
  fun liveConnectConfig_javaSourceWrittenAgainstTheReleasedApi_compiles() {
    // Arrange: distinct values for the directly expressible params; the complex object params stay
    // null (the all-19-distinct reflection case above already covers forwarding).
    val caller =
      compileJava(
        "ReleasedLiveConnectConfigCaller",
        """
        import com.google.adk.kt.types.LiveConnectConfig;

        public final class ReleasedLiveConnectConfigCaller {
          public static LiveConnectConfig create() {
            return new LiveConnectConfig(
                null, 0.1f, 0.2f, 3, 4, null, 6, null, null, true, null, null, null, null,
                null, null, null, null, null);
          }
        }
        """,
      )

    // Act
    val config = caller.getMethod("create").invoke(null) as LiveConnectConfig

    // Assert
    assertEquals(0.1f, config.temperature)
    assertEquals(0.2f, config.topP)
    assertEquals(3, config.topK)
    assertEquals(4, config.maxOutputTokens)
    assertEquals(6, config.seed)
    assertEquals(true, config.enableAffectiveDialog)
    assertNull(config.explicitVadSignal)
  }

  @Test
  fun event_releasedFullConstructor_stillLinks() {
    // Arrange
    val arguments =
      with(RELEASED_EVENT) {
        arrayOf<Any?>(
          id,
          invocationId,
          author,
          content,
          actions,
          longRunningToolIds,
          partial,
          turnComplete,
          errorCode,
          errorMessage,
          finishReason,
          usageMetadata,
          avgLogProbs,
          interrupted,
          branch,
          groundingMetadata,
          modelVersion,
          citationMetadata,
          cacheMetadata,
          customMetadata,
          output,
          nodeInfo,
          timestamp,
        )
      }

    // Act
    val event = Event::class.java.getConstructor(*RELEASED_EVENT_PARAMETERS).newInstance(*arguments)

    // Assert
    assertEquals(RELEASED_EVENT, event)
  }

  @Test
  fun event_javaSourceWrittenAgainstTheReleasedApi_compiles() {
    // Arrange
    val caller =
      compileJava(
        "ReleasedEventCaller",
        """
        import com.google.adk.kt.events.Event;
        import com.google.adk.kt.events.EventActions;
        import java.util.Set;

        public final class ReleasedEventCaller {
          public static Event create() {
            return new Event(
                "evt-1", null, "agent", null, new EventActions(), Set.of(), false, false, null,
                null, null, null, null, false, null, null, null, null, null, null, null, null,
                1234L);
          }
        }
        """,
      )

    // Act
    val event = caller.getMethod("create").invoke(null) as Event

    // Assert
    assertEquals(Event(id = "evt-1", author = "agent", timestamp = 1234L), event)
  }

  @Test
  fun event_releasedNoArgConstructor_stillLinks() {
    // Arrange / Act: the released class had a no-arg constructor; all its params had defaults.
    val event = Event::class.java.getConstructor().newInstance()

    // Assert
    assertEquals(Event(id = event.id, timestamp = event.timestamp), event)
  }

  @Test
  fun voiceActivity_javaSourceReadsAudioOffsetMillis() {
    // Arrange
    val reader =
      compileJava(
        "VoiceActivityReader",
        """
        import com.google.adk.kt.types.VoiceActivity;

        public final class VoiceActivityReader {
          public static Long read(VoiceActivity activity) {
            return activity.audioOffsetMillis();
          }
        }
        """,
      )

    // Act
    val millis =
      reader
        .getMethod("read", VoiceActivity::class.java)
        .invoke(null, VoiceActivity(audioOffset = 1_500.milliseconds))

    // Assert
    assertEquals(1_500L, millis)
  }

  /** Compiles [source] with javac against the test classpath and loads [className]. */
  private fun compileJava(className: String, source: String): Class<*> {
    val compiler = checkNotNull(ToolProvider.getSystemJavaCompiler()) { "javac is unavailable." }
    val directory = createTempDirectory("released-api-java")
    val sourceFile = directory.resolve("$className.java").apply { writeText(source.trimIndent()) }
    val errors = ByteArrayOutputStream()
    val exitCode =
      compiler.run(
        null,
        null,
        errors,
        "-proc:none",
        "-classpath",
        System.getProperty("java.class.path"),
        "-d",
        directory.toString(),
        sourceFile.toString(),
      )
    assertTrue(exitCode == 0, "javac failed:\n$errors")
    return URLClassLoader(arrayOf(directory.toUri().toURL()), javaClass.classLoader)
      .loadClass(className)
  }

  private companion object {
    val RELEASED_APP_PARAMETERS: Array<Class<*>> =
      arrayOf(
        String::class.java,
        BaseAgent::class.java,
        List::class.java,
        ResumabilityConfig::class.java,
        EventsCompactionConfig::class.java,
        ContextCacheConfig::class.java,
      )

    val RELEASED_CONTEXT_PARAMETERS: Array<Class<*>> =
      arrayOf(
        Session::class.java,
        RunConfig::class.java,
        BaseAgent::class.java,
        String::class.java,
        String::class.java,
        ArtifactService::class.java,
        MemoryService::class.java,
        SessionService::class.java,
        ResumabilityConfig::class.java,
        EventsCompactionConfig::class.java,
        ContextCacheConfig::class.java,
        Content::class.java,
        Map::class.java,
        Map::class.java,
        Map::class.java,
        ContextFrameworkData::class.java,
        Boolean::class.java,
        PluginManager::class.java,
        InvocationCostManager::class.java,
      )

    val RELEASED_RUN_CONFIG_PARAMETERS: Array<Class<*>> =
      arrayOf(StreamingMode::class.java, Int::class.java, Map::class.java)

    val RELEASED_LIVE_CONNECT_CONFIG_PARAMETERS: Array<Class<*>> =
      arrayOf(
        List::class.java,
        Float::class.javaObjectType,
        Float::class.javaObjectType,
        Int::class.javaObjectType,
        Int::class.javaObjectType,
        MediaResolution::class.java,
        Int::class.javaObjectType,
        SpeechConfig::class.java,
        ThinkingConfig::class.java,
        Boolean::class.javaObjectType,
        Content::class.java,
        List::class.java,
        SessionResumptionConfig::class.java,
        AudioTranscriptionConfig::class.java,
        AudioTranscriptionConfig::class.java,
        RealtimeInputConfig::class.java,
        ContextWindowCompressionConfig::class.java,
        ProactivityConfig::class.java,
        List::class.java,
      )

    val RELEASED_LLM_RESPONSE_PARAMETERS: Array<Class<*>> =
      arrayOf(
        Content::class.java,
        UsageMetadata::class.java,
        FinishReason::class.java,
        String::class.java,
        Boolean::class.java,
        Boolean::class.java,
        String::class.java,
        CitationMetadata::class.java,
        GroundingMetadata::class.java,
        String::class.java,
        Map::class.java,
        Double::class.javaObjectType,
        LogprobsResult::class.java,
        CacheMetadata::class.java,
      )

    val RELEASED_EVENT_PARAMETERS: Array<Class<*>> =
      arrayOf(
        String::class.java,
        String::class.java,
        String::class.java,
        Content::class.java,
        EventActions::class.java,
        Set::class.java,
        Boolean::class.java,
        Boolean::class.java,
        String::class.java,
        String::class.java,
        FinishReason::class.java,
        UsageMetadata::class.java,
        Double::class.javaObjectType,
        Boolean::class.java,
        String::class.java,
        GroundingMetadata::class.java,
        String::class.java,
        CitationMetadata::class.java,
        CacheMetadata::class.java,
        Map::class.java,
        Any::class.java,
        NodeInfo::class.java,
        Long::class.java,
      )

    /**
     * A distinct, non-default value for every released parameter, so a swapped or dropped argument
     * fails.
     */
    val RELEASED_EVENT =
      Event(
        id = "evt-1",
        invocationId = "inv-1",
        author = "agent",
        content = Content(role = "model", parts = listOf(Part(text = "hi"))),
        actions = EventActions(skipSummarization = true),
        longRunningToolIds = setOf("call-1"),
        partial = true,
        turnComplete = true,
        errorCode = "E1",
        errorMessage = "failed",
        finishReason = FinishReason.STOP,
        usageMetadata = UsageMetadata(totalTokenCount = 7),
        avgLogProbs = -0.5,
        interrupted = true,
        branch = "root.child",
        groundingMetadata = GroundingMetadata(webSearchQueries = listOf("q")),
        modelVersion = "v1",
        citationMetadata = CitationMetadata(listOf(Citation(uri = "https://example.com"))),
        cacheMetadata = CacheMetadata(fingerprint = "fp", contentsCount = 2),
        customMetadata = mapOf("k" to "v"),
        output = "result",
        nodeInfo = NodeInfo(path = "wf@1"),
        timestamp = 1234L,
      )
  }
}
